import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { EmotionCacheProvider } from "./providers/MuiThemeProvider/EmotionCacheProvider";
import { ThemeProvider } from "./providers/MuiThemeProvider/MuiThemeProviderr";
import { Header } from "./components/Header";
import { Main } from "./components/Main/Main";

const roboto = Roboto({
 weight:[ "400","700"],
 subsets: ["latin"],

});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <EmotionCacheProvider>
        <ThemeProvider>
          <Header />
          <Main>
          {children}
          </Main>
          </ThemeProvider>
        </EmotionCacheProvider>
      </body>
    </html>
  );
}
